version: '3.8'

services:
    nginx:
      #container_name: nginx
      build:
        context: docker
        dockerfile: dev/nginx/Dockerfile
      volumes:
        - ./app:/app
      ports:
        - "80:80"

    fpm:
      #container_name: fpm
      build:
        context: docker
        dockerfile: dev/php-fpm/Dockerfile
      volumes:
        - ./app:/app
      environment:
        APP_DEBUG: 1
      depends_on:
        - nginx

    cli:
      #container_name: cli
      build:
        context: docker
        dockerfile: dev/php-cli/Dockerfile
      volumes:
        - ./app:/app
      environment:
        APP_DEBUG: 1


